name: Release CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: TRYING TO REACH ENB
        env: # Set the secret as an input
          CANE: ${{ secrets.CANE }}
        run: echo "$CANE AND $env.CANE"
